# Generated by Django 5.0.2 on 2024-02-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"verbose_name": "dish", "verbose_name_plural": "dishes"},
        ),
    ]
