# Generated by Django 5.0.2 on 2024-02-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
